### ISSUE TITLE
Update Github issue and PR labels for Magasin

### ISSUE THREAD

**Issue by frahugo** [civilcode/magasin-platform#46]

**Comment by bokay** [comment]
@nicholasjhenry @frahugo It is just a matter of running the following command:

`~/.asdf/installs/nodejs/8.11.2/.npm/lib/node_modules/github-labels/bin/labels -c .github/labels.json civilcode/magasin-platform` (with the right nodejs version)

or

`labels -c .github/labels.json civilcode/magasin-platform`

depending on how nodejs is setup on the local machine, with github-labels installed locally(`npm install github-labels -g`)

However, I'm not authorized to perform this action. Can one of you run this task please?

**Comment by nicholasjhenry** [comment]
@frahugo are you able to run this? I'm getting the same error as @bokay:

```
Token created!
>> Authorize error
```

**Comment by frahugo** [comment]
You have to specify the token on the command line. Maybe the instructions were not migrated to the guide. See the previous content of the README in magasin here: https://github.com/civilcode/magasin-platform/commit/a1a86f905da55b86850a89355817bafb5676a122 <https://github.com/civilcode/magasin-platform/commit/a1a86f905da55b86850a89355817bafb5676a122>

**Comment by nicholasjhenry** [comment]
@frahugo Obviously, I didn't read the instructions correctly ;-)

https://github.com/civilcode/magasin-platform/blob/cc306c653ea9995139e01d8f1633fb41c2fb0624/.github/SETUP.md
